export {CardsRouter} from'./cards'
export { AppRouter } from './App'
export { aiRouter } from './ai'
export { CardArrayRouter } from './cardarray'
export { MajorsRouter } from './majors'
export { LayoutsRouter } from './layout'
export { UserRouter } from './user'